### ISSUE TITLE
添加链接后显示找不到文件

### ISSUE THREAD

**Issue by zuimengren** [Clinton-Abraham/UPLOADER-BOT#25]
添加链接后显示找不到文件
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/dispatcher.py", line 222, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/UPLOADER-BOT/plugins/callback.py", line 20, in button
    await youtube_dl_call_back(bot, update)
  File "/root/UPLOADER-BOT/plugins/youtube_dl_button.py", line 182, in youtube_dl_call_back
    file_size = os.stat(download_directory).st_size
FileNotFoundError: [Errno 2] No such file or directory: './DOWNLOADS/664700723/index_2000.mkv'

**Comment by Clinton-Abraham** [comment]
Send me that url bro....

**Comment by zuimengren** [comment]
> 

任意文件都不行
